export const countries = [
  { name: 'Uruguay', dialCode: '+598', code: 'UY' },
  { name: 'Brazil', dialCode: '+55', code: 'BR' },
  { name: 'Argentina', dialCode: '+54', code: 'AR' },
  { name: 'Canada', dialCode: '+1', code: 'CA' },
  { name: 'Mexico', dialCode: '+52', code: 'MX' },
  { name: 'Bolivia', dialCode: '+591', code: 'BO' },
  { name: 'Ecuador', dialCode: '+593', code: 'EC' },
  { name: 'Peru', dialCode: '+51', code: 'PE' },
  { name: 'Colombia', dialCode: '+57', code: 'CO' },
    { name: 'Paraguay', dialCode: '+595', code: 'PY' },
    { name: 'Chile', dialCode: '+56', code: 'CL' },
    { name: 'United States', dialCode: '+1', code: 'US' },
    { name: 'Costa Rica', dialCode: '+506', code: 'CR' },
    { name: 'Panama', dialCode: '+507', code: 'PA' },
    { name: 'Venezuela', dialCode: '+58', code: 'VE' },
    { name: 'Guatemala', dialCode: '+502', code: 'GT' },
    { name: 'El Salvador', dialCode: '+503', code: 'SV' },
    { name: 'Haiti', dialCode: '+509', code: 'HT' },
    { name: 'Belize', dialCode: '+501', code: 'BZ' },
    { name: 'Honduras', dialCode: '+504', code: 'HN' },
    { name: 'Nicaragua', dialCode: '+505', code: 'NI' },
    { name: 'Dominican Republic', dialCode: '+1-809', code: 'DO' },
    { name: 'Cuba', dialCode: '+53', code: 'CU' },
    { name: 'Puerto Rico', dialCode: '+1-787', code: 'PR' },
    { name: 'Bahamas', dialCode: '+1-242', code: 'BS' },
    { name: 'Barbados', dialCode: '+1-246', code: 'BB' },
    { name: 'Jamaica', dialCode: '+1-876', code: 'JM' },
    { name: 'Trinidad and Tobago', dialCode: '+1-868', code: 'TT' },
    { name: 'Saint Kitts and Nevis', dialCode: '+1-869', code: 'KN' },
    { name: 'Saint Lucia', dialCode: '+1-758', code: 'LC' },
    { name: 'Saint Vincent and the Grenadines', dialCode: '+1-784', code: 'VC' },
    { name: 'Antigua and Barbuda', dialCode: '+1-268', code: 'AG' },
    { name: 'Dominica', dialCode: '+1-767', code: 'DM' },
    { name: 'Grenada', dialCode: '+1-473', code: 'GD' },
    { name: 'Guyana', dialCode: '+592', code: 'GY' },
    { name: 'Suriname', dialCode: '+597', code: 'SR' },
  ];
  